context:
  name: dynamixel-sdk
  version: "4.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ROBOTIS-GIT/DynamixelSDK/archive/refs/tags/${{ version }}.tar.gz
  sha256: 966f656f38b9024839088add589fe90553db21b85a2cc12669209a2d25dda772

build:
  script: python -m pip install ./python -vv
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - pyserial

tests:
  - python:
      imports:
        - dynamixel_sdk
      pip_check: true
      python_version:
        - ${{ python_min }}.*

about:
  homepage: https://github.com/ROBOTIS-GIT/DynamixelSDK
  summary: 'ROBOTIS Dynamixel SDK (Protocol1.0/2.0).'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
