context:
  name: dynamixel-sdk
  version: "4.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ROBOTIS-GIT/DynamixelSDK/archive/refs/tags/${{ version }}.tar.gz
  sha256: 2be40b73fbb6a2efb26314bc7927e81fb40bafa1043cf05611d1d1f940610d82

build:
  script: python -m pip install ./python -vv
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - pyserial

tests:
  - python:
      imports:
        - dynamixel_sdk
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/ROBOTIS-GIT/DynamixelSDK
  summary: 'ROBOTIS Dynamixel SDK (Protocol1.0/2.0).'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
